import sys
import os

# --- Ensure project root is on path ---
PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

import streamlit as st
from multi_symbol_engine import generate_signals_multi


st.set_page_config(
    page_title="AI Trading System V2",
    layout="wide"
)

st.title("📊 AI Trading System — Signal Dashboard (V2)")
st.caption("Read-only signal intelligence • No auto trading")

# --- Sidebar Filters ---
st.sidebar.header("Filters")

signal_filter = st.sidebar.multiselect(
    "Signal",
    ["BUY", "SELL", "HOLD"],
    default=["BUY", "SELL"]
)

quality_filter = st.sidebar.multiselect(
    "Quality",
    ["STRONG", "MEDIUM", "WEAK"],
    default=["STRONG", "MEDIUM"]
)

# --- Main Input ---
symbols_input = st.text_input(
    "Enter symbols (comma separated)",
    "TATASTEEL"
)

if st.button("Generate Signals"):
    symbols = [s.strip().upper() for s in symbols_input.split(",") if s.strip()]
    results = generate_signals_multi(symbols)

    st.subheader("Generated Signals")

    if not results:
        st.warning("No signals generated by engine.")
    else:
        # Always show raw count
        st.caption(f"Total signals generated: {len(results)}")

        filtered = [
            r for r in results
            if r.get("signal") in signal_filter
            and r.get("quality") in quality_filter
        ]

        if not filtered:
            st.warning("No signals match selected filters. Try adjusting filters.")
            st.dataframe(results, use_container_width=True)
        else:
            st.dataframe(filtered, use_container_width=True)
