import pandas as pd
from collections import Counter

def audit_decisions(results):
    """
    results: list of dicts generated by multi_symbol_engine
    """

    df = pd.DataFrame(results)

    print("\n================ DECISION AUDIT REPORT ================\n")

    # 1️⃣ Action Distribution
    action_counts = Counter(df["signal"])
    total = len(df)

    print("1️⃣ ACTION DISTRIBUTION")
    for action, count in action_counts.items():
        print(f"  {action}: {count} ({round(count/total*100, 2)}%)")

    # 2️⃣ Quality Distribution
    print("\n2️⃣ QUALITY DISTRIBUTION")
    quality_counts = Counter(df["quality"])
    for q, count in quality_counts.items():
        print(f"  {q}: {count} ({round(count/total*100, 2)}%)")

    # 3️⃣ TA vs FA Conflict Analysis
    print("\n3️⃣ TA vs FA CONFLICT CHECK")

    conflicts = df[
        (df["ta_signal"].isin(["BUY", "SELL"])) &
        (df["fa_signal"].isin(["BULLISH", "BEARISH"])) &
        (
            ((df["ta_signal"] == "BUY") & (df["fa_signal"] == "BEARISH")) |
            ((df["ta_signal"] == "SELL") & (df["fa_signal"] == "BULLISH"))
        )
    ]

    if conflicts.empty:
        print("  ✅ No unresolved TA–FA conflicts")
    else:
        print(f"  ⚠️ Conflicts detected: {len(conflicts)}")
        print(conflicts[[
            "time", "symbol",
            "ta_signal", "fa_signal",
            "signal", "quality"
        ]])

    # 4️⃣ Over-Trading Risk Check
    print("\n4️⃣ OVER-TRADING CHECK")
    aggressive = df[df["signal"].isin(["BUY", "SELL"])]
    print(f"  Actionable signals: {len(aggressive)} / {total}")

    if len(aggressive) / total > 0.6:
        print("  ⚠️ Risk: Too many actionable signals")
    else:
        print("  ✅ Discipline maintained")

    # 5️⃣ Human Confidence Verdict
    print("\n5️⃣ HUMAN CONFIDENCE VERDICT")
    strong_actions = df[df["quality"] == "STRONG"]
    if strong_actions.empty:
        print("  ⚠️ No STRONG signals — system very conservative")
    else:
        print(f"  ✅ STRONG signals count: {len(strong_actions)}")

    print("\n================ END OF AUDIT =================\n")
